theme: jekyll-theme-minimal
title: Zief homepage
description: Welcome to my github site. Thankyou for come here.

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Article
    url: /article
